name: ai-quickstart
channels:
  - conda-forge
dependencies:
  - annotated-types=0.7.0
  - anyio=4.12.1
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - certifi=2026.1.4
  - distro=1.9.0
  - exceptiongroup=1.3.1
  - h11=0.16.0
  - h2=4.3.0
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=78.2
  - idna=3.11
  - jiter=0.13.0
  - libexpat=2.7.3
  - libffi=3.5.2
  - liblzma=5.8.2
  - libmpdec=4.0.0
  - libsqlite=3.51.2
  - libzlib=1.3.1
  - ncurses=6.5
  - openai=2.20.0
  - openssl=3.6.1
  - pip=26.0.1
  - pydantic=2.12.5
  - pydantic-core=2.41.5
  - python=3.14.3
  - python-dotenv=1.2.1
  - python_abi=3.14
  - readline=8.3
  - sniffio=1.3.1
  - tk=8.6.13
  - tqdm=4.67.3
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - tzdata=2025c
  - zstd=1.5.7

